packages:
  - packages/*
  - website
  - examples/*/*
allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
autoInstallPeers: false
catalog:
  '@types/react': ^19.2.4
  '@types/react-dom': ^19.2.3
  react: ^19.2.0
  react-dom: ^19.2.0
overrides:
  '@nano_kit/next-router@*': workspace:^
  '@nano_kit/query@*': workspace:^
  '@nano_kit/react-router@*': workspace:^
  '@nano_kit/react-ssr@*': workspace:^
  '@nano_kit/react@*': workspace:^
  '@nano_kit/router@*': workspace:^
  '@nano_kit/ssr@*': workspace:^
  '@nano_kit/store@*': workspace:^
  'nanoviews@*': workspace:^
