packages:
  - packages/*
  - website
  - examples/*/*
allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
autoInstallPeers: false
catalog:
  '@preact/preset-vite': ^2.10.2
  '@types/react': ^19.2.4
  '@types/react-dom': ^19.2.3
  '@testing-library/dom': ^10.0.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/preact': ^3.2.4
  '@testing-library/react': ^16.1.0
  '@testing-library/user-event': ^14.5.2
  '@vitejs/plugin-react': ^6.0.1
  '@vitest/coverage-v8': ^4.1.4
  '@size-limit/preset-small-lib': ^12.0.0
  happy-dom: ^20.0.0
  preact: ^10.27.1
  preact-render-to-string: ^6.6.1
  react: ^19.2.0
  react-dom: ^19.2.0
  size-limit: ^12.0.0
  storybook: ^10.3.5
  typescript: ^6.0.0
  vite: ^8.0.8
  vitest: ^4.1.4
overrides:
  '@nano_kit/cookie-store@*': workspace:^
  '@nano_kit/next-router@*': workspace:^
  '@nano_kit/preact@*': workspace:^
  '@nano_kit/preact-router@*': workspace:^
  '@nano_kit/preact-ssr@*': workspace:^
  '@nano_kit/platform-web@*': workspace:^
  '@nano_kit/query@*': workspace:^
  '@nano_kit/react-router@*': workspace:^
  '@nano_kit/react-ssr@*': workspace:^
  '@nano_kit/react@*': workspace:^
  '@nano_kit/router@*': workspace:^
  '@nano_kit/ssr@*': workspace:^
  '@nano_kit/store@*': workspace:^
  'nanoviews@*': workspace:^
