import { join } from 'node:path'
import { convertPage } from './convert.js'
import {
  pagesOf,
  skillsOf
} from './skills.js'

const HEADER = '<!-- Generated by skills-docs from the documentation sources. Do not edit by hand. -->'

async function generateSkill(skill, { docs, skills, site, drop, out }) {
  const pages = (await Promise.all(skill.entries.map(entry => pagesOf(docs, entry)))).flat()
  const sections = await Promise.all(pages.map(path => convertPage(path, {
    docs,
    site,
    tabs: skill.tabs,
    drop
  })))

  return {
    name: skill.name,
    target: join(skills, skill.name, out),
    content: `${HEADER}\n\n${sections.filter(Boolean).join('\n\n---\n\n')}\n`
  }
}

// Builds the documentation file of every skill that declares docs pages
export async function generate(options) {
  const skills = await skillsOf(options.skills, options.tabs)

  return Promise.all(skills.map(skill => generateSkill(skill, options)))
}
