/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationLocationIdRouteImport } from './routes/location.$locationId'
import { Route as EpisodeEpisodeIdRouteImport } from './routes/episode.$episodeId'
import { Route as CharacterCharacterIdRouteImport } from './routes/character.$characterId'

const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLocationIdRoute = LocationLocationIdRouteImport.update({
  id: '/location/$locationId',
  path: '/location/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeEpisodeIdRoute = EpisodeEpisodeIdRouteImport.update({
  id: '/episode/$episodeId',
  path: '/episode/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCharacterIdRoute = CharacterCharacterIdRouteImport.update({
  id: '/character/$characterId',
  path: '/character/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/episodes': typeof EpisodesRoute
  '/locations': typeof LocationsRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/location/$locationId': typeof LocationLocationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/episodes': typeof EpisodesRoute
  '/locations': typeof LocationsRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/location/$locationId': typeof LocationLocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/episodes': typeof EpisodesRoute
  '/locations': typeof LocationsRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/location/$locationId': typeof LocationLocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/character/$characterId'
    | '/episode/$episodeId'
    | '/location/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/character/$characterId'
    | '/episode/$episodeId'
    | '/location/$locationId'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/character/$characterId'
    | '/episode/$episodeId'
    | '/location/$locationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  EpisodesRoute: typeof EpisodesRoute
  LocationsRoute: typeof LocationsRoute
  CharacterCharacterIdRoute: typeof CharacterCharacterIdRoute
  EpisodeEpisodeIdRoute: typeof EpisodeEpisodeIdRoute
  LocationLocationIdRoute: typeof LocationLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$episodeId': {
      id: '/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/episode/$episodeId'
      preLoaderRoute: typeof EpisodeEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$characterId': {
      id: '/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/character/$characterId'
      preLoaderRoute: typeof CharacterCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  EpisodesRoute: EpisodesRoute,
  LocationsRoute: LocationsRoute,
  CharacterCharacterIdRoute: CharacterCharacterIdRoute,
  EpisodeEpisodeIdRoute: EpisodeEpisodeIdRoute,
  LocationLocationIdRoute: LocationLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
